version: '3.9'

services:
  client:
    image: node:alpine
    env_file: .env
    ports:
      - 3333:3000
    command: npm run watch
    restart: unless-stopped
    depends_on:
      mongo_db:
        condition: service_healthy
    links:
      - mongo_db
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app/
    networks:
      - ntwrk_mn

  mongo_db:
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 50s
    image: mongo
    ports:
      - 27018:27017
    command: mongod
    env_file: .env
    volumes:
      - ./db/data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - ntwrk_mn

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: .env
    restart: unless-stopped
    depends_on:
      mongo_db:
        condition: service_healthy
    networks:
      - ntwrk_mn

networks:
  ntwrk_mn:
    driver: bridge
